[package]
name = "phasesmith-model"
description = "Application-neutral domain records for PhaseSmith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
phasesmith-core = { version = "0.1.0", path = "../phasesmith-core" }
phasesmith-engine = { version = "0.1.0", path = "../phasesmith-engine" }

[lints]
workspace = true
