"""Fast, validated powder-diffraction profile calculations.

The equations shared by the Python and Rust APIs are documented at
https://phasesmith.readthedocs.io/en/latest/mathematics/.
"""

import importlib as _importlib
import warnings as _warnings
from importlib.metadata import PackageNotFoundError, version

from . import (
    automation,
    background,
    fpa_calibration,
    integrations,
    persistence,
    profile_estimation,
    refinement,
)
from ._api import (
    PARAMETER_ORDER,
    TCH_PARAMETER_ORDER,
    ProfileResult,
    TchFwhmShape,
    TchProfileResult,
    TchSigmaProfileResult,
    TchSigmaShape,
    accumulate,
    accumulate_tch,
    profile,
    profile_tch,
    profile_tch_from_gaussian_sigma,
    tch_shape_from_fwhm,
    tch_shape_from_gaussian_sigma,
)
from .background import (
    XYPATTERN_REVISION,
    BackgroundSubtractionResult,
    SmoothBrucknerBackground,
    smooth_bruckner,
)
from .calculation import (
    CalculationOptions,
    PreparedPattern,
    calculate_cw_pattern,
    calculate_monochromatic_cw_pattern,
    calculate_monochromatic_pattern,
    calculate_neutron_fcj_pattern,
    calculate_neutron_pattern,
    calculate_pattern,
)
from .control import (
    CancellationCallback,
    CancellationToken,
    OperationCancelled,
    ProgressCallback,
    ProgressEvent,
)
from .crystallography import (
    CELL_PARAMETER_NAMES,
    MAX_DENSE_DERIVATIVE_ELEMENTS,
    AtomSiteBatch,
    CellGeometry,
    DSpacingResult,
    P1JvpResult,
    P1StructureFactorResult,
    P1VjpResult,
    StructureFactorResult,
    StructureFactorValuesResult,
    UnitCell,
    calculate_p1_structure_factors,
    calculate_structure_factor_values,
    calculate_structure_factors,
    p1_intensity_transpose_jacobian_vector_product,
    p1_jacobian_vector_product,
    p1_parameter_names,
)
from .cw import (
    CW_GLOBAL_PARAMETER_ORDER,
    CW_LOCAL_PARAMETER_ORDER,
    CwProfileParameters,
    accumulate_cw,
    accumulate_cw_components,
    accumulate_cw_contributions,
    cw_profile_parameters,
)
from .execution import ExecutionPolicy
from .extensions import (
    PHYSICS_PROVIDER_API_VERSION,
    CompositePhysicsProvider,
    PhysicsContext,
    PhysicsContribution,
    ProviderDescriptor,
    ReflectionPhysicsProvider,
)
from .fcj import (
    CW_FCJ_GLOBAL_PARAMETER_ORDER,
    CW_FCJ_LOCAL_PARAMETER_ORDER,
    FCJ_PARAMETER_ORDER,
    FcjProfileResult,
    accumulate_cw_fcj,
    accumulate_cw_fcj_components,
    profile_fcj,
)
from .fpa_calibration import (
    BraggBrentanoFundamentalProfile,
    FundamentalEmissionLine,
    FundamentalPeakDiagnostic,
    FundamentalPeakPattern,
    FundamentalProfileCalibrationOptions,
    FundamentalProfileCalibrationResult,
    GaussianSpectralPassband,
    SollerAxialGeometry,
    calibrate_fundamental_profile,
    simulate_fundamental_peaks,
)
from .instrument import (
    ConstantWavelengthInstrument,
    FcjGeometry,
    TofBankGeometry,
    TofIncidentSpectrum,
    TofIncidentSpectrumEvaluation,
    TofInstrument,
)
from .intensity_corrections import (
    BraggBrentanoPolarizedLp,
    BraggBrentanoUnpolarizedLp,
    ConstantWavelengthNeutronLorentz,
    IntegratedIntensityCorrection,
    IntegratedIntensityCorrectionProvider,
    NeutralIntegratedIntensityCorrection,
    TimeOfFlightNeutronLorentz,
    evaluate_intensity_correction,
)
from .pattern import (
    PatternCalculationResult,
    PhasePatternComponent,
    PowderPattern,
    StructuralPatternCalculationResult,
    StructuralPatternJvpResult,
    StructuralPatternLinearizationResult,
    StructuralPatternVjpResult,
    StructuralReflectionResult,
    TofPowderPattern,
)
from .phase import (
    Phase,
    ReciprocalMetric,
    ReflectionBatch,
    ReflectionGeometryBatch,
    RietveldPhase,
    StructuralReflectionBatch,
)
from .profile_estimation import (
    ProfileEstimationMode,
    ProfileEstimationOptions,
    ProfileEstimationResult,
    ProfileEstimationStage,
    estimate_effective_profile,
    starting_profile_from_fwhm,
)
from .project import RietveldProject
from .quantitative import (
    PhaseWeightFraction,
    QuantitativePhase,
    QuantitativePhaseAnalysis,
    quantitative_phase_analysis,
    quantitative_phase_analysis_with_covariance,
    weight_fractions_from_scale,
)
from .radiation import (
    BraggBrentanoGeometry,
    ComponentRadiation,
    ConstantWavelengthExperiment,
    DebyeScherrerGeometry,
    MonochromaticRadiation,
    RadiationProbe,
    WavelengthComponents,
)
from .results import AccumulationResult, PatternDerivatives, SupportJacobian
from .sample import (
    IsotropicLorentzianMicrostrainBroadening,
    IsotropicMicrostrainBroadening,
    IsotropicSizeBroadening,
    MarchDollasePreferredOrientation,
    ReciprocalAngleGeometry,
    StephensOrthorhombicBroadening,
    reciprocal_angle_geometry,
)
from .scattering import (
    NEUTRON_NUCLEAR_DESCRIPTOR,
    NEUTRON_TABLE_PROVENANCE,
    SCATTERING_PROVIDER_API_VERSION,
    XRAY_FIXED_DISPERSION_DESCRIPTOR,
    XRAY_NON_RESONANT_DESCRIPTOR,
    XRAY_TABLE_PROVENANCE,
    NeutronNuclear,
    NeutronSpeciesMetadata,
    PreparedNeutronNuclear,
    PreparedXrayNonResonant,
    ScatteringContext,
    ScatteringFactorBatch,
    ScatteringFactorProvider,
    ScatteringProviderDescriptor,
    ScatteringSpecies,
    ScatteringTableProvenance,
    XrayFixedDispersion,
    XrayNonResonant,
    XraySpeciesMetadata,
    evaluate_scattering_provider,
    neutron_species_metadata,
    species_from_structure,
    xray_species_metadata,
)
from .structural_calculation import PreparedStructuralPattern, calculate_structural_pattern
from .structure import (
    AnisotropicDisplacement,
    AtomSite,
    CrystalStructure,
    StructureDiagnostic,
    StructureSource,
    structure_from_record,
    structure_to_record,
)
from .symmetry import (
    DEFAULT_MAX_REFLECTION_CANDIDATES,
    CwTwoThetaRange,
    DSpacingRange,
    ExpandedSites,
    GeneratedReflectionBatch,
    MetricConstraints,
    PreparedReflectionGenerator,
    ReflectionFamilies,
    ReflectionRange,
    ScatteringVectorRange,
    SpaceGroup,
    SymmetryOperation,
    TofRange,
)
from .terminal import TerminalCancellationController
from .tof import (
    TOF_GLOBAL_PARAMETER_ORDER,
    TOF_LOCAL_PARAMETER_ORDER,
    TofProfileParameters,
    TofProfileResult,
    accumulate_tof,
    profile_tof,
    tof_profile_parameters,
)

try:
    __version__ = version("phasesmith")
except PackageNotFoundError:  # pragma: no cover - source tree without installation
    __version__ = "0+unknown"

__all__ = [
    "CELL_PARAMETER_NAMES",
    "CW_FCJ_GLOBAL_PARAMETER_ORDER",
    "CW_FCJ_LOCAL_PARAMETER_ORDER",
    "CW_GLOBAL_PARAMETER_ORDER",
    "CW_LOCAL_PARAMETER_ORDER",
    "DEFAULT_MAX_REFLECTION_CANDIDATES",
    "FCJ_PARAMETER_ORDER",
    "MAX_DENSE_DERIVATIVE_ELEMENTS",
    "NEUTRON_NUCLEAR_DESCRIPTOR",
    "NEUTRON_TABLE_PROVENANCE",
    "PARAMETER_ORDER",
    "PHYSICS_PROVIDER_API_VERSION",
    "SCATTERING_PROVIDER_API_VERSION",
    "TCH_PARAMETER_ORDER",
    "TOF_GLOBAL_PARAMETER_ORDER",
    "TOF_LOCAL_PARAMETER_ORDER",
    "XRAY_FIXED_DISPERSION_DESCRIPTOR",
    "XRAY_NON_RESONANT_DESCRIPTOR",
    "XRAY_TABLE_PROVENANCE",
    "XYPATTERN_REVISION",
    "AccumulationResult",
    "AnisotropicDisplacement",
    "AtomSite",
    "AtomSiteBatch",
    "BackgroundSubtractionResult",
    "BraggBrentanoFundamentalProfile",
    "BraggBrentanoGeometry",
    "BraggBrentanoPolarizedLp",
    "BraggBrentanoUnpolarizedLp",
    "CalculationOptions",
    "CancellationCallback",
    "CancellationToken",
    "CellGeometry",
    "ComponentRadiation",
    "CompositePhysicsProvider",
    "ConstantWavelengthExperiment",
    "ConstantWavelengthInstrument",
    "ConstantWavelengthNeutronLorentz",
    "CrystalStructure",
    "CwProfileParameters",
    "CwTwoThetaRange",
    "DSpacingRange",
    "DSpacingResult",
    "DebyeScherrerGeometry",
    "ExecutionPolicy",
    "ExpandedSites",
    "FcjGeometry",
    "FcjProfileResult",
    "FundamentalEmissionLine",
    "FundamentalPeakDiagnostic",
    "FundamentalPeakPattern",
    "FundamentalProfileCalibrationOptions",
    "FundamentalProfileCalibrationResult",
    "GaussianSpectralPassband",
    "GeneratedReflectionBatch",
    "IntegratedIntensityCorrection",
    "IntegratedIntensityCorrectionProvider",
    "IsotropicLorentzianMicrostrainBroadening",
    "IsotropicMicrostrainBroadening",
    "IsotropicSizeBroadening",
    "MarchDollasePreferredOrientation",
    "MetricConstraints",
    "MonochromaticRadiation",
    "NeutralIntegratedIntensityCorrection",
    "NeutronNuclear",
    "NeutronSpeciesMetadata",
    "OperationCancelled",
    "P1JvpResult",
    "P1StructureFactorResult",
    "P1VjpResult",
    "PatternCalculationResult",
    "PatternDerivatives",
    "Phase",
    "PhasePatternComponent",
    "PhaseWeightFraction",
    "PhysicsContext",
    "PhysicsContribution",
    "PowderPattern",
    "PreparedNeutronNuclear",
    "PreparedPattern",
    "PreparedReflectionGenerator",
    "PreparedStructuralPattern",
    "PreparedXrayNonResonant",
    "ProfileEstimationMode",
    "ProfileEstimationOptions",
    "ProfileEstimationResult",
    "ProfileEstimationStage",
    "ProfileResult",
    "ProgressCallback",
    "ProgressEvent",
    "ProviderDescriptor",
    "QuantitativePhase",
    "QuantitativePhaseAnalysis",
    "RadiationProbe",
    "ReciprocalAngleGeometry",
    "ReciprocalMetric",
    "ReflectionBatch",
    "ReflectionFamilies",
    "ReflectionGeometryBatch",
    "ReflectionPhysicsProvider",
    "ReflectionRange",
    "RietveldPhase",
    "RietveldProject",
    "ScatteringContext",
    "ScatteringFactorBatch",
    "ScatteringFactorProvider",
    "ScatteringProviderDescriptor",
    "ScatteringSpecies",
    "ScatteringTableProvenance",
    "ScatteringVectorRange",
    "SmoothBrucknerBackground",
    "SollerAxialGeometry",
    "SpaceGroup",
    "StephensOrthorhombicBroadening",
    "StructuralPatternCalculationResult",
    "StructuralPatternJvpResult",
    "StructuralPatternLinearizationResult",
    "StructuralPatternVjpResult",
    "StructuralReflectionBatch",
    "StructuralReflectionResult",
    "StructureDiagnostic",
    "StructureFactorResult",
    "StructureFactorValuesResult",
    "StructureSource",
    "SupportJacobian",
    "SymmetryOperation",
    "TchFwhmShape",
    "TchProfileResult",
    "TchSigmaProfileResult",
    "TchSigmaShape",
    "TerminalCancellationController",
    "TimeOfFlightNeutronLorentz",
    "TofBankGeometry",
    "TofIncidentSpectrum",
    "TofIncidentSpectrumEvaluation",
    "TofInstrument",
    "TofPowderPattern",
    "TofProfileParameters",
    "TofProfileResult",
    "TofRange",
    "UnitCell",
    "WavelengthComponents",
    "XrayFixedDispersion",
    "XrayNonResonant",
    "XraySpeciesMetadata",
    "__version__",
    "accumulate",
    "accumulate_cw",
    "accumulate_cw_components",
    "accumulate_cw_contributions",
    "accumulate_cw_fcj",
    "accumulate_cw_fcj_components",
    "accumulate_tch",
    "accumulate_tof",
    "automation",
    "background",
    "calculate_cw_pattern",
    "calculate_monochromatic_cw_pattern",
    "calculate_monochromatic_pattern",
    "calculate_neutron_fcj_pattern",
    "calculate_neutron_pattern",
    "calculate_p1_structure_factors",
    "calculate_pattern",
    "calculate_structural_pattern",
    "calculate_structure_factor_values",
    "calculate_structure_factors",
    "calibrate_fundamental_profile",
    "cw_profile_parameters",
    "estimate_effective_profile",
    "evaluate_intensity_correction",
    "evaluate_scattering_provider",
    "fpa_calibration",
    "integrations",
    "neutron_species_metadata",
    "p1_intensity_transpose_jacobian_vector_product",
    "p1_jacobian_vector_product",
    "p1_parameter_names",
    "persistence",
    "profile",
    "profile_estimation",
    "profile_fcj",
    "profile_tch",
    "profile_tch_from_gaussian_sigma",
    "profile_tof",
    "quantitative_phase_analysis",
    "quantitative_phase_analysis_with_covariance",
    "reciprocal_angle_geometry",
    "refinement",
    "simulate_fundamental_peaks",
    "smooth_bruckner",
    "species_from_structure",
    "starting_profile_from_fwhm",
    "structure_from_record",
    "structure_to_record",
    "tch_shape_from_fwhm",
    "tch_shape_from_gaussian_sigma",
    "tof_profile_parameters",
    "weight_fractions_from_scale",
    "xray_species_metadata",
]

_DEPRECATED_EXPORT_MODULES = {
    "phasesmith.automation": {
        "ADVISOR_CONTEXT_SCHEMA",
        "ADVISOR_PACKET_SCHEMA",
        "AUTOMATION_ERROR_SCHEMA",
        "RECIPE_LINT_SCHEMA",
        "RECIPE_PROPOSAL_SCHEMA",
        "RESUME_RESULT_SCHEMA",
        "REVIEW_PACKET_SCHEMA",
        "WORKFLOW_PLAN_SCHEMA",
        "WORKFLOW_RESULT_SCHEMA",
        "WORKFLOW_REVIEW_SCHEMA",
        "WORKFLOW_SPEC_SCHEMA",
        "AdvisorContext",
        "AutomationError",
        "ProposerProvenance",
        "RecipeProposal",
        "ResumeRunResult",
        "WorkflowLineage",
        "WorkflowOutputs",
        "WorkflowPlan",
        "WorkflowRunResult",
        "WorkflowSpec",
        "advisor_packet",
        "automation_schema",
        "automation_schema_names",
        "inspect_cif_file",
        "inspect_powder_file",
        "lint_recipe_proposal",
        "lint_recipe_proposal_file",
        "load_recipe_proposal",
        "load_workflow_plan",
        "load_workflow_spec",
        "parse_recipe_proposal",
        "plan_workflow",
        "prepare_review_packet",
        "recipe_proposal_schema",
        "replan_workflow",
        "resume_workflow",
        "review_workflow_output",
        "run_workflow",
        "workflow_spec_schema",
        "write_workflow_plan",
    },
    "phasesmith.io.cif": {
        "CifBackend",
        "CifReadLimits",
        "CifReadResult",
        "NativeCifBackend",
        "read_cif",
    },
    "phasesmith.io.powder": {
        "PowderData",
        "PowderFormat",
        "PowderReadLimits",
        "TofPowderData",
        "TofPowderFormat",
        "read_powder_data",
        "read_tof_powder_data",
    },
    "phasesmith.io.space_groups": {
        "SpaceGroupInfo",
        "space_group_by_number",
        "space_group_by_symbol",
        "space_group_from_hall_symbol",
    },
    "phasesmith.io.tof_instrument": {
        "GsasTofInstrumentData",
        "GsasTofInstrumentReadLimits",
        "read_gsas_tof_instrument",
    },
    "phasesmith.refinement.readiness": {
        "ReadinessSeverity",
        "RietveldReadinessDiagnostic",
        "RietveldReadinessReport",
        "review_rietveld_input",
    },
    "phasesmith.reporting": {
        "rietveld_result_record",
        "write_rietveld_csv",
        "write_rietveld_json",
    },
}
_DEPRECATED_EXPORTS = {
    name: module_name for module_name, names in _DEPRECATED_EXPORT_MODULES.items() for name in names
}


def __getattr__(name: str) -> object:
    """Resolve one-release-cycle compatibility aliases for module-owned APIs."""

    module_name = _DEPRECATED_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    _warnings.warn(
        f"phasesmith.{name} moved to {module_name}.{name}; "
        "the top-level alias is deprecated and will be removed in 1.0",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(_importlib.import_module(module_name), name)
    globals()[name] = value
    return value
