"""Explicit, provenance-aware external validation datasets."""

from .datasets import (
    VALIDATION_DATASETS,
    ExternalValidationFile,
    ValidationDataset,
    fetch_validation_dataset,
    validation_dataset,
    verify_validation_dataset,
)
from .real_data import (
    QARR_1G_CUKA_FIXED_DISPERSION,
    QARR_1G_WEIGHED_WEIGHT_FRACTIONS,
    RealDataValidationReport,
    ValidationCheck,
    qarr_1g_readiness,
    run_echidna_lab6_validation,
    run_nist_srm660c_validation,
    run_pbso4_cw_validation,
    run_powgen_tof_readiness,
    run_powgen_tof_validation,
    run_qarr_1g_validation,
    run_qarr_1h_validation,
    run_sucrose_lebail_validation,
)
from .suite import (
    VALIDATION_CASES,
    ValidationCase,
    build_validation_suite_record,
    compare_validation_suite_records,
    run_validation_case,
    scientific_fingerprint,
    scientific_record,
)

__all__ = [
    "QARR_1G_CUKA_FIXED_DISPERSION",
    "QARR_1G_WEIGHED_WEIGHT_FRACTIONS",
    "VALIDATION_CASES",
    "VALIDATION_DATASETS",
    "ExternalValidationFile",
    "RealDataValidationReport",
    "ValidationCase",
    "ValidationCheck",
    "ValidationDataset",
    "build_validation_suite_record",
    "compare_validation_suite_records",
    "fetch_validation_dataset",
    "qarr_1g_readiness",
    "run_echidna_lab6_validation",
    "run_nist_srm660c_validation",
    "run_pbso4_cw_validation",
    "run_powgen_tof_readiness",
    "run_powgen_tof_validation",
    "run_qarr_1g_validation",
    "run_qarr_1h_validation",
    "run_sucrose_lebail_validation",
    "run_validation_case",
    "scientific_fingerprint",
    "scientific_record",
    "validation_dataset",
    "verify_validation_dataset",
]
