"""Shared refinement infrastructure and method-specific submodules."""

from .core import (
    AffineConstraint,
    Bounds,
    ConstraintTransform,
    FixedConstraint,
    LeastSquaresOptimizer,
    ParameterKey,
    ParameterSet,
    ParameterSpec,
    ResidualEvaluation,
    ResidualOptions,
    TerminationReason,
    evaluate_residuals,
    jacobian_vector_product,
    transpose_jacobian_vector_product,
)
from .lebail import (
    CoincidentReflectionGroup,
    IntensityExtractionResult,
    IterationRecord,
    LeBailCheckpoint,
    LeBailInput,
    LeBailOptions,
    LeBailPhase,
    LeBailResult,
    ParameterChange,
    ReflectionIntensity,
    build_parameter_set,
    extract_intensities,
    initialize_intensities,
    instrument_parameter_key,
    iterate_once,
    phase_scale_key,
    refine,
    reflection_position_key,
)
from .scipy import ScipyLeastSquaresAdapter

__all__ = [
    "AffineConstraint",
    "Bounds",
    "CoincidentReflectionGroup",
    "ConstraintTransform",
    "FixedConstraint",
    "IntensityExtractionResult",
    "IterationRecord",
    "LeBailCheckpoint",
    "LeBailInput",
    "LeBailOptions",
    "LeBailPhase",
    "LeBailResult",
    "LeastSquaresOptimizer",
    "ParameterChange",
    "ParameterKey",
    "ParameterSet",
    "ParameterSpec",
    "ReflectionIntensity",
    "ResidualEvaluation",
    "ResidualOptions",
    "ScipyLeastSquaresAdapter",
    "TerminationReason",
    "build_parameter_set",
    "evaluate_residuals",
    "extract_intensities",
    "initialize_intensities",
    "instrument_parameter_key",
    "iterate_once",
    "jacobian_vector_product",
    "phase_scale_key",
    "refine",
    "reflection_position_key",
    "transpose_jacobian_vector_product",
]
