"""Fast, validated powder-diffraction profile calculations."""

from ._api import (
    PARAMETER_ORDER,
    TCH_PARAMETER_ORDER,
    ProfileResult,
    TchFwhmShape,
    TchProfileResult,
    TchSigmaProfileResult,
    TchSigmaShape,
    accumulate,
    accumulate_tch,
    profile,
    profile_tch,
    profile_tch_from_gaussian_sigma,
    tch_shape_from_fwhm,
    tch_shape_from_gaussian_sigma,
)
from .calculation import (
    CalculationOptions,
    PreparedPattern,
    calculate_cw_pattern,
    calculate_monochromatic_cw_pattern,
    calculate_monochromatic_pattern,
    calculate_neutron_fcj_pattern,
    calculate_neutron_pattern,
    calculate_pattern,
)
from .control import (
    CancellationCallback,
    OperationCancelled,
    ProgressCallback,
    ProgressEvent,
)
from .cw import (
    CW_GLOBAL_PARAMETER_ORDER,
    CW_LOCAL_PARAMETER_ORDER,
    CwProfileParameters,
    accumulate_cw,
    accumulate_cw_components,
    accumulate_cw_contributions,
    cw_profile_parameters,
)
from .extensions import (
    PHYSICS_PROVIDER_API_VERSION,
    CompositePhysicsProvider,
    PhysicsContext,
    PhysicsContribution,
    ProviderDescriptor,
    ReflectionPhysicsProvider,
)
from .fcj import (
    CW_FCJ_GLOBAL_PARAMETER_ORDER,
    CW_FCJ_LOCAL_PARAMETER_ORDER,
    FCJ_PARAMETER_ORDER,
    FcjProfileResult,
    accumulate_cw_fcj,
    accumulate_cw_fcj_components,
    profile_fcj,
)
from .instrument import ConstantWavelengthInstrument, FcjGeometry, TofInstrument
from .pattern import (
    PatternCalculationResult,
    PhasePatternComponent,
    PowderPattern,
)
from .phase import Phase, ReciprocalMetric, ReflectionBatch, ReflectionGeometryBatch
from .radiation import (
    ConstantWavelengthExperiment,
    MonochromaticRadiation,
    RadiationProbe,
    WavelengthComponents,
)
from .results import AccumulationResult, PatternDerivatives, SupportJacobian
from .sample import (
    IsotropicMicrostrainBroadening,
    IsotropicSizeBroadening,
    MarchDollasePreferredOrientation,
    ReciprocalAngleGeometry,
    reciprocal_angle_geometry,
)

__all__ = [
    "CW_FCJ_GLOBAL_PARAMETER_ORDER",
    "CW_FCJ_LOCAL_PARAMETER_ORDER",
    "CW_GLOBAL_PARAMETER_ORDER",
    "CW_LOCAL_PARAMETER_ORDER",
    "FCJ_PARAMETER_ORDER",
    "PARAMETER_ORDER",
    "PHYSICS_PROVIDER_API_VERSION",
    "TCH_PARAMETER_ORDER",
    "AccumulationResult",
    "CalculationOptions",
    "CancellationCallback",
    "CompositePhysicsProvider",
    "ConstantWavelengthExperiment",
    "ConstantWavelengthInstrument",
    "CwProfileParameters",
    "FcjGeometry",
    "FcjProfileResult",
    "IsotropicMicrostrainBroadening",
    "IsotropicSizeBroadening",
    "MarchDollasePreferredOrientation",
    "MonochromaticRadiation",
    "OperationCancelled",
    "PatternCalculationResult",
    "PatternDerivatives",
    "Phase",
    "PhasePatternComponent",
    "PhysicsContext",
    "PhysicsContribution",
    "PowderPattern",
    "PreparedPattern",
    "ProfileResult",
    "ProgressCallback",
    "ProgressEvent",
    "ProviderDescriptor",
    "RadiationProbe",
    "ReciprocalAngleGeometry",
    "ReciprocalMetric",
    "ReflectionBatch",
    "ReflectionGeometryBatch",
    "ReflectionPhysicsProvider",
    "SupportJacobian",
    "TchFwhmShape",
    "TchProfileResult",
    "TchSigmaProfileResult",
    "TchSigmaShape",
    "WavelengthComponents",
    "accumulate",
    "accumulate_cw",
    "accumulate_cw_components",
    "accumulate_cw_contributions",
    "accumulate_cw_fcj",
    "accumulate_cw_fcj_components",
    "accumulate_tch",
    "calculate_cw_pattern",
    "calculate_monochromatic_cw_pattern",
    "calculate_monochromatic_pattern",
    "calculate_neutron_fcj_pattern",
    "calculate_neutron_pattern",
    "calculate_pattern",
    "cw_profile_parameters",
    "profile",
    "profile_fcj",
    "profile_tch",
    "profile_tch_from_gaussian_sigma",
    "reciprocal_angle_geometry",
    "tch_shape_from_fwhm",
    "tch_shape_from_gaussian_sigma",
]
