"""Fast, validated powder-diffraction profile calculations."""

from ._api import (
    PARAMETER_ORDER,
    TCH_PARAMETER_ORDER,
    AccumulationResult,
    PatternDerivatives,
    ProfileResult,
    SupportJacobian,
    TchFwhmShape,
    TchProfileResult,
    TchSigmaProfileResult,
    TchSigmaShape,
    accumulate,
    accumulate_tch,
    profile,
    profile_tch,
    profile_tch_from_gaussian_sigma,
    tch_shape_from_fwhm,
    tch_shape_from_gaussian_sigma,
)

__all__ = [
    "PARAMETER_ORDER",
    "TCH_PARAMETER_ORDER",
    "AccumulationResult",
    "PatternDerivatives",
    "ProfileResult",
    "SupportJacobian",
    "TchFwhmShape",
    "TchProfileResult",
    "TchSigmaProfileResult",
    "TchSigmaShape",
    "accumulate",
    "accumulate_tch",
    "profile",
    "profile_tch",
    "profile_tch_from_gaussian_sigma",
    "tch_shape_from_fwhm",
    "tch_shape_from_gaussian_sigma",
]
