#!/usr/bin/env python3
"""Synchronize the canonical rustdoc mathematics into the MkDocs site."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUSTDOC_DIR = ROOT / "crates" / "phasesmith-rs" / "src" / "guide" / "mathematics"
MKDOCS_DIR = ROOT / "docs" / "mathematics"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/sync_math_docs.py from the canonical rustdoc source. -->"
)


@dataclass(frozen=True)
class Page:
    source: str
    output: str
    python_modules: tuple[str, ...]
    rustdoc_slug: str
    related_docs: tuple[tuple[str, str], ...] = ()


PAGES = (
    Page("index.md", "index.md", (), ""),
    Page(
        "peak_profiles.md",
        "peak-profiles.md",
        ("phasesmith", "phasesmith.cw", "phasesmith.fcj", "phasesmith.tof"),
        "peak_profiles",
        (
            ("Pseudo-Voigt units and storage", "../equations.md"),
            ("TCH derivation and sources", "../tch-profile.md"),
            ("CW broadening", "../cw-profile.md"),
            ("FCJ derivation and sources", "../fcj-profile.md"),
            ("Wavelength components", "../wavelength-components.md"),
            ("Neutron CW", "../neutron-cw.md"),
            ("Neutron TOF derivation and sources", "../tof-profile.md"),
        ),
    ),
    Page(
        "crystallography.md",
        "crystallography.md",
        (
            "phasesmith.crystallography",
            "phasesmith.symmetry",
            "phasesmith.scattering",
            "phasesmith.intensity_corrections",
        ),
        "crystallography",
        (
            ("Cell and P1 foundation", "../crystallography-foundation.md"),
            ("Symmetry and reflections", "../symmetry-reflections.md"),
            ("Scattering models and data provenance", "../scattering-models.md"),
            ("Structural intensities and sources", "../structural-intensities.md"),
            ("Lattice refinement", "../lattice-refinement.md"),
        ),
    ),
    Page(
        "pattern_composition.md",
        "pattern-composition.md",
        ("phasesmith.calculation", "phasesmith.structural_calculation", "phasesmith.sample"),
        "pattern_composition",
        (
            ("Multi-phase composition", "../multiphase.md"),
            ("Structural wavelength components", "../structural-wavelength-components.md"),
            ("Sample physics derivations and sources", "../sample-physics.md"),
        ),
    ),
    Page(
        "backgrounds.md",
        "backgrounds.md",
        ("phasesmith.background", "phasesmith.refinement.background"),
        "backgrounds",
        (("Background subtraction workflow", "../background-subtraction.md"),),
    ),
    Page(
        "refinement.md",
        "refinement.md",
        (
            "phasesmith.refinement",
            "phasesmith.refinement.lebail",
            "phasesmith.refinement.rietveld",
            "phasesmith.quantitative",
        ),
        "refinement",
        (
            ("Le Bail extraction", "../lebail.md"),
            ("Shared refinement infrastructure", "../refinement.md"),
            ("Rietveld workflow", "../rietveld.md"),
            ("Quantitative phase analysis and source", "../quantitative-phase-analysis.md"),
        ),
    ),
)


def _replace_rust_links(text: str) -> str:
    result = re.sub(r"\[`crate::([^`]+)`\]", r"`phasesmith::\1` (Rust)", text)
    if "[`crate::" in result:
        raise ValueError("unsupported rustdoc intra-doc link in mathematical page")
    return result


def _replace_required(text: str, old: str, new: str, *, context: str) -> str:
    if old not in text:
        raise ValueError(f"expected {context} was not found in canonical rustdoc")
    return text.replace(old, new, 1)


def _render_index(source: str) -> str:
    source = _replace_required(
        source,
        "These pages define the mathematical models currently implemented by the\n"
        "published Rust crates. Equations are rendered as plain, copyable text so the\n"
        "reference works on docs.rs and in offline `cargo doc` output without external\n"
        "JavaScript or a math-rendering service.\n",
        "These pages define the mathematical models implemented by PhaseSmith's native\n"
        "Rust kernels and exposed through both the Rust and Python APIs. Python does not\n"
        "reimplement these production equations: its typed scripting interface calls the\n"
        "same kernels used by native applications.\n\n"
        "Equations use plain, copyable text so this reference works offline and does not\n"
        "depend on JavaScript or an external math-rendering service.\n",
        context="mathematical-reference introduction",
    )
    source, link_definition_count = re.subn(r"\n\[`[^`]+`\]: crate::[^\n]+", "", source)
    if link_definition_count != 5:
        raise ValueError("expected five rustdoc mathematical-page link definitions")
    replacements = {
        "[`peak_profiles`]": "[Peak profiles](peak-profiles.md)",
        "[`crystallography`]": "[Crystallography](crystallography.md)",
        "[`pattern_composition`]": "[Pattern composition](pattern-composition.md)",
        "[`backgrounds`]": "[Backgrounds](backgrounds.md)",
        "[`refinement`]": "[Refinement](refinement.md)",
    }
    for rust_link, mkdocs_link in replacements.items():
        source = _replace_required(
            source,
            rust_link,
            mkdocs_link,
            context=f"index link {rust_link}",
        )
    source = _replace_required(
        source,
        "Every section names the Rust module or type that owns the equation. Models not\n",
        "Every section names the native Rust owner and corresponding public Python modules.\n"
        "Models not\n",
        context="API-owner explanation",
    )
    source = _replace_required(
        source,
        "angular Rust APIs",
        "angular public APIs",
        context="shared angular-unit convention",
    )
    return f"{GENERATED_NOTICE}\n\n{source.rstrip()}\n"


def _render_page(source: str, page: Page) -> str:
    title, separator, body = source.partition("\n")
    if not separator or not title.startswith("# "):
        raise ValueError(f"{page.source} must start with a level-one heading")
    module_list = ", ".join(f"`{module}`" for module in page.python_modules)
    shared_note = (
        '!!! note "Shared Rust/Python model"\n'
        "    These equations define the native implementation used by both APIs.\n"
        f"    Python users reach it through {module_list}. The Rust owner names below\n"
        "    identify implementation boundaries; they do not imply a separate Python model.\n"
    )
    rustdoc_url = (
        f"https://docs.rs/phasesmith/latest/phasesmith/guide/mathematics/{page.rustdoc_slug}/"
    )
    navigation = (
        "## API navigation\n\n"
        "- [Python API map](../api-reference.md)\n"
        f"- [Rust API reference for these equations]({rustdoc_url})\n"
    )
    if page.related_docs:
        navigation += "\n### Detailed derivations and provenance\n\n"
        navigation += "".join(f"- [{title}]({path})\n" for title, path in page.related_docs)
    body = _replace_rust_links(body).rstrip()
    return f"{GENERATED_NOTICE}\n\n{title}\n\n{shared_note}\n{body}\n\n{navigation}"


def render(page: Page) -> str:
    source = (RUSTDOC_DIR / page.source).read_text(encoding="utf-8")
    if page.source == "index.md":
        return _render_index(source)
    return _render_page(source, page)


def check() -> bool:
    current = True
    for page in PAGES:
        destination = MKDOCS_DIR / page.output
        expected = render(page)
        actual = destination.read_text(encoding="utf-8") if destination.exists() else ""
        if actual == expected:
            continue
        current = False
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(destination),
            tofile=f"generated from {page.source}",
            lineterm="",
        )
        print("\n".join(diff), file=sys.stderr)
    return current


def write() -> None:
    MKDOCS_DIR.mkdir(parents=True, exist_ok=True)
    for page in PAGES:
        (MKDOCS_DIR / page.output).write_text(render(page), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed MkDocs pages differ from the canonical rustdoc source",
    )
    args = parser.parse_args()
    if args.check:
        return 0 if check() else 1
    write()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
