#!/usr/bin/env python3
"""Generate bundled skill resources and their public documentation without imports."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILL_NAME = "phasesmith-ai-workflows"
NOTICE = "<!-- Generated by scripts/sync_skill.py; edit skills/phasesmith-ai-workflows/. -->\n\n"
INTRO = """# Agent skill

PhaseSmith ships a portable agent skill with its Python distribution. It gives
an agent the operating protocol and scientific interpretation rules for the
installed version. No model-provider SDK, source checkout, or GSAS-II is needed.
The instructions below and the linked references are generated from the same
canonical files as the bundled skill; CI and release checks reject drift.

## Read or install it

```shell
phasesmith skill --path
phasesmith skill --print
phasesmith skill --print experiment
phasesmith skill --print workflow
phasesmith skill --print interpretation
phasesmith skill --print all
```

`--path` prints the absolute directory containing `SKILL.md`, `references/`,
and optional agent UI metadata. `--print` emits UTF-8 text, not JSON. Invalid
arguments and missing resources use the CLI's JSON errors and exit status 2.
These commands only read local resources; they neither refine data nor install
or modify agent configuration. The bundled instructions match the installed
distribution; online `latest` documentation can describe a newer build.

To install the skill, copy the **whole directory** returned by `--path` into
your agent's supported skills location, retaining the name
`phasesmith-ai-workflows`. Use your agent's normal skill installation mechanism;
discovery paths differ between hosts. Do not copy only `SKILL.md`, because it
links to supporting references. Refresh the copy when upgrading PhaseSmith.
An agent without skill discovery can read `--print all` as instructions.

For the complete CLI tutorial, see [AI-guided automation](../ai-automation.md).
The skill guides using PhaseSmith; repository `AGENTS.md` guides development of
PhaseSmith itself. See [documentation development](../documentation.md) for
maintaining the canonical files and checking the generated copies.

## Skill instructions

"""


def generated_files(root: Path) -> dict[Path, bytes]:
    """Map each managed output to bytes derived solely from canonical sources."""
    source = root / "skills" / SKILL_NAME
    package = root / "python" / "phasesmith" / "_skills" / SKILL_NAME
    docs = root / "docs" / "agent-skill"
    outputs: dict[Path, bytes] = {}
    for path in sorted(source.rglob("*")):
        if not path.is_file() or path.suffix not in {".md", ".yaml"}:
            continue
        relative = path.relative_to(source)
        outputs[package / relative] = path.read_bytes()
        if relative == Path("SKILL.md"):
            text = path.read_text(encoding="utf-8")
            if not text.startswith("---\n") or "\n---\n" not in text[4:]:
                raise ValueError("SKILL.md must have YAML frontmatter")
            body = text[4:].split("\n---\n", 1)[1].lstrip()
            # The page supplies its own title; all remaining headings move one level down.
            _, separator, body = body.partition("\n")
            if not separator:
                raise ValueError("SKILL.md must have a title and body")
            body = re.sub(r"^(#{1,5}) ", r"\1# ", body.lstrip(), flags=re.MULTILINE)
            outputs[docs / "index.md"] = (NOTICE + INTRO + body).encode("utf-8")
        elif relative.parts[0] == "references" and path.suffix == ".md":
            outputs[docs / relative] = NOTICE.encode("utf-8") + path.read_bytes()
    if package / "SKILL.md" not in outputs:
        raise ValueError(f"missing canonical skill: {source / 'SKILL.md'}")
    return outputs


def sync(root: Path, *, check: bool) -> bool:
    outputs = generated_files(root)
    managed = (
        root / "python" / "phasesmith" / "_skills" / SKILL_NAME,
        root / "docs" / "agent-skill",
    )
    stale = [
        path
        for directory in managed
        for path in directory.rglob("*")
        if path.is_file() and path not in outputs
    ]
    changed = [
        path for path, data in outputs.items() if not path.exists() or path.read_bytes() != data
    ]
    if check:
        for path in sorted([*stale, *changed]):
            print(f"stale skill output: {path.relative_to(root)}", file=sys.stderr)
        if stale or changed:
            print("Run python scripts/sync_skill.py and review the diff.", file=sys.stderr)
        return not stale and not changed
    for path in stale:
        path.unlink()
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(outputs[path])
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="reject stale outputs without writing")
    args = parser.parse_args()
    return 0 if sync(ROOT, check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
