[package]
name = "phasesmith-io"
description = "Native file-format adapters for PhaseSmith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
moyo = "=0.15.0"
phasesmith-crystallography = { path = "../phasesmith-crystallography" }
phasesmith-model = { path = "../phasesmith-model" }

[lints]
workspace = true
