[package]
name = "phasesmith-io"
description = "Native file-format adapters for PhaseSmith"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
moyo = "=0.15.0"
phasesmith-core = { version = "0.2.0", path = "../phasesmith-core" }
phasesmith-crystallography = { version = "0.2.0", path = "../phasesmith-crystallography" }
phasesmith-model = { version = "0.2.0", path = "../phasesmith-model" }

[lints]
workspace = true
